version: "3"
services:
  postgres:
    container_name: application
    image: postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
